### ISSUE TITLE
Issue with Multi-monitor setups:

### ISSUE THREAD

**Issue by saintphaenixos** [omegaui/cliptopia#1]
Hello!

I found your app through Reddit, I really enjoy what this is trying to do, and downloaded it immediately.

I have your first Github issue however: When opening with a multimonitor setup, it opens across two monitors:
![image](https://github.com/omegaui/cliptopia/assets/25014799/62bba30e-2383-4dc1-9261-11010752287e)

Because of this I can't see how to close the app, unfortunately it also isn't receiving anything from my clipboard. (I may have to check my Java installation.)

Appreciate your help. :+1: Love the idea of this app so far!

Also, I'm on Ubuntu 23.10, running the Proprietary Nvidia Driver.

**Comment by omegaui** [comment]
Hi!

Thank you for posting this issue.
And Don't worry, I myself do not have a multi-monitor so I never thought of this issue.
BTW, Cliptopia's home OS is Ubuntu 23.10 only (thats my daily driver these days), so any issue you will face, me too.

Good part: I'll add a window size customization section in the next update.

Also, I do not actually know how multi monitors work together and why it is stretching to the next monitor, are they two different screens? a bit of help from you will allow me to fix this as soon as possible.


Thank You for your feedback.

**Comment by omegaui** [comment]
> unfortunately it also isn't receiving anything from my clipboard. (I may have to check my Java installation.)

Recording the clipboard is not managed by Java btw,
Make sure the background daemon is active by running `cliptopia-daemon --status`.

**Comment by omegaui** [comment]
Actually, the idea about covering the screen is,

- Cliptopia starts
- Fetches the screen size
- Expands its bound onto the available area

I can see in the ss, GNOME Desktop is not stretching so far, this seems odd, as it fetches the screen size from the compositor I guess?.

Also a relief part, Cliptopia not only works in power mode (which you are seeing right now).
It can also work in a dense mode just launch it from you app launcher if you have installed it from the repo's installer.
or you can alternatively run `cliptopia --silent` to launch it in dense mode, **until the fix arrives**.


Here's how it looks ...
![image](https://github.com/omegaui/cliptopia/assets/73544069/8f58fabc-05d6-4729-9e0d-dc0df05570ab)
![Screenshot from 2023-12-13 13-00-57](https://github.com/omegaui/cliptopia/assets/73544069/95a2f6a3-12eb-4eab-a4d4-41d138215a83)

**Comment by omegaui** [comment]
BTW, you can close the app by pressing ESCAPE key.

**Comment by saintphaenixos** [comment]
> Hi!
> 
> Thank you for posting this issue. And Don't worry, I myself do not have a multi-monitor so I never thought of this issue. BTW, Cliptopia's home OS is Ubuntu 23.10 only (thats my daily driver these days), so any issue you will face, me too.
> 
> Good part: I'll add a window size customization section in the next update.
> 
> Also, I do not actually know how multi monitors work together and why it is stretching to the next monitor, are they two different screens? a bit of help from you will allow me to fix this as soon as possible.
> 
> Thank You for your feedback.

So they are separate monitors, both are 1920x1080 I actually have a tri monitor setup, and the app opens in the middle screen and then takes over the right monitor. It doesn't show at all on the left most one. I do think it's very convenient we are on the same OS, so this should go fast.

> > unfortunately it also isn't receiving anything from my clipboard. (I may have to check my Java installation.)
> 
> Recording the clipboard is not managed by Java btw, Make sure the background daemon is active by running `cliptopia-daemon --status`.

Hrmmm, Okay, when I'm at my workstation this morning I'll give it another go and report back. I coulda swore it was running.

> Actually, the idea about covering the screen is,
> 
> * Cliptopia starts
> * Fetches the screen size
> * Expands its bound onto the available area
> 
> I can see in the ss, GNOME Desktop is not stretching so far, this seems odd, as it fetches the screen size from the compositor I guess?.
> 
> Also a relief part, Cliptopia not only works in power mode (which you are seeing right now). It can also work in a dense mode just launch it from you app launcher if you have installed it from the repo's installer. or you can alternatively run `cliptopia --silent` to launch it in dense mode, **until the fix arrives**.

It has a dense mode? Oh well that'll make it at least useful for me for now. I'll give that a shot.

> BTW, you can close the app by pressing ESCAPE key.

I did eventually figure that out. lol thankfully.

**Comment by omegaui** [comment]
The recent commit might fix your issue, Please let me know.

**Comment by omegaui** [comment]
![Screenshot from 2023-12-13 21-33-15](https://github.com/omegaui/cliptopia/assets/73544069/5b2bc70a-90a4-4029-a36f-39b28bf326c8)

Also, support for wayland using wl-clipboard has arrived today.

**Comment by saintphaenixos** [comment]
> The recent commit might fix your issue, Please let me know.

I gave it a shot and ran into an installation problem see issue #6

**Comment by saintphaenixos** [comment]
> The recent commit might fix your issue, Please let me know.

So I just re-installed from source, since that's functioning right now, and the window is coming up only on one monitor!

The only issue is that it's my right most monitor now and I don't seem to have a choice on how to switch which one it pops up on, as opposed to any other monitor. But it's functional!

**Comment by omegaui** [comment]
Thanks for feedback, I'll add an option in the app soon to select the monitor too :wink: .

**Comment by saintphaenixos** [comment]
Would you prefer that this be closed out? Or left open until monitor switching has been implemented? Because you've fixed my original issue. :)

**Comment by saintphaenixos** [comment]
> > unfortunately it also isn't receiving anything from my clipboard. (I may have to check my Java installation.)
> 
> Recording the clipboard is not managed by Java btw, Make sure the background daemon is active by running `cliptopia-daemon --status`.

Okay, I see my problem with this now, I was still running into it. I could get the window open, but no clips. I didn't realize that you needed to hit the little alert that was in place of the gear here: 
![image](https://github.com/omegaui/cliptopia/assets/25014799/953075ba-c3ae-4814-b24d-c78d6bd47912)

Now my daemon is running, though I'm still having an issue with it, I'm going to open another issue for just that, as that isn't the same as this issue.

**Comment by omegaui** [comment]
> Would you prefer that this be closed out? Or left open until monitor switching has been implemented? Because you've fixed my original issue. :)

Once the monitor selection arrives, I'll close this as completed.

**Comment by omegaui** [comment]
![screenshot](https://github.com/omegaui/cliptopia/assets/73544069/6fc2a52d-b33f-49fd-89ef-9c4c99dd1e3f)
