### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by sbstn87** [omegaui/cliptopia#4]
Hi,

will you consider a Windows version in the future?

**Comment by omegaui** [comment]
Windows is a close source software,
Also, windows already has native clipboard management with limited features.
I don't think and in the future also I will be wanting to have windows support.
That's very tricky there.

But, if there is someone out there, then, they can use Cliptopia's source code to have at least a UI ready to do such things.
BTW, the [daemon](https://github.com/omegaui/cliptopia_daemon) is the only part which needs reimplementation in terms of Windows os.
