### ISSUE TITLE
Daemon not capturing text:

### ISSUE THREAD

**Issue by saintphaenixos** [omegaui/cliptopia#9]
So I've got one additional issue with the daemon capturing text.

I've installed from source, and am running into this problem:
[Screencast from 2023-12-13 12-15-03.webm](https://github.com/omegaui/cliptopia/assets/25014799/5c3a643e-4d0f-4475-9232-45dd60465352)

I can copy text, but nothing shows in the clipboard.

running: 
`cliptopia-daemon --status
`
returns:
`Daemon Status: Alive`

**Comment by omegaui** [comment]
This seems strange,
thank you for following so long,

Can you open up a terminal and try running
```
cliptopia-daemon --restart --debug
```

this will output the logs onto the terminal, and then try doing the copy thing again.

**Comment by saintphaenixos** [comment]
Alrighty, ran it, and here we go:
[Screencast from 2023-12-13 13-32-06.webm](https://github.com/omegaui/cliptopia/assets/25014799/1406ec1c-d358-4658-b4ad-f83b56f80f50)

I didn't get much output unfortunately to work with.

**Comment by saintphaenixos** [comment]
> This seems strange, thank you for following so long,

No worries, helping out with this has been fun.

**Comment by omegaui** [comment]
@saintphaenixos 
I did a reclone and reinstall from source, I can see it working both in Wayland & X11.
Can you please try enabling force xclip mode ...
![image](https://github.com/omegaui/cliptopia/assets/73544069/cfd9a132-47d5-47d6-be86-5c02850d3aaa)

**Comment by omegaui** [comment]
The recent commits might have fixed this issue.
If not you may reopen this issue.
